# Site settings
baseurl = "https://garado.dev/rocks"
languageCode = "en-us"
title = "Alexis's Rock/Mineral/Fossil Collection"
theme = "gallery"

[params]
  defaultTheme = "dark"
  title = "Alexis's Rock/Mineral/Fossil Collection"
  description = "I like geology."

  [author]
    name = "Alexis Garado"
    homepage = "https://garado.dev/rocks"

  [outputs]
    home = ["HTML", "RSS"]
    page = ["HTML"]
    section = ["HTML"]
  
  [imaging]
    quality = 75
    resampleFilter = "CatmullRom"
    [imaging.exif]
      disableDate = false
      disableLatLong = true
      includeFields = "ImageDescription|Orientation"
  
  [menu]
    [[menu.footer]]
      name = "GitHub"
      url = "https://github.com/nicokaiser/hugo-theme-gallery/"
      weight = 3
  
  [services]
    [services.rss]
      limit = 100
