# Site settings
baseurl = "http://example.org/"
languageCode = "en-us"
title = "Alexis's Rock/Mineral/Fossil Collection"
theme = "hugrid"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
# Meta
title = "Alexis's Rock/Mineral/Fossil Collection"
subtitle = "I like geology."
author = "author"
description = "Hugrid - grid theme for Hugo with an expanding image preview."

# Body background color
bodybgcolor = "#f9f9f9"

# Preview container button text
buttontext = "See more"

# Footer text
footertext = ""

# add extra-css
# custom_css = ['css/extra1.css', 'css/extra2.css']
